# IntelliJ Platform Artifacts Repositories -> https://plugins.jetbrains.com/docs/intellij/intellij-artifacts.html

pluginGroup = com.github.enciyo.ghcheideaplugin
pluginName = gh-che-idea-plugin
pluginRepositoryUrl = https://github.com/enciyo/gh-che-idea-plugin
pluginVersion = 0.0.5
pluginSinceBuild = 242
pluginUntilBuild=
platformType = IC
platformVersion = 2024.2.4

platformPlugins = com.github.copilot:1.5.65-242
platformBundledPlugins =
gradleVersion = 9.3.1
kotlin.stdlib.default.dependency=false
org.gradle.configuration-cache=false
org.gradle.caching=false
--add-exports=java.base/jdk.internal.vm=ALL-UNNAMED

# Plugin Verification IDE Targets (TYPE:VERSION format, comma separated)
